Downloads/W3schools-With-Django-master/config/urls.py
from django.contrib import admin
from django.urls import path, include
from w3school.accounts.views import home, page1, page2
urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('w3school.accounts.urls')),
  path('', home, name="home"),
  path('page1/', page1, name="page1"),
  path('page2/', page2, name="page2"),
]

Downloads/W3schools-With-Django-master/w3school/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views as core_view

app_name = 'accounts'

urlpatterns = [
  path(r'^login/$', auth_view.LoginView.as_view(template_name='accounts/login.html'), name='login'),
  path(r'^logout/$', auth_view.LogoutView.as_view(), name='logout'),
  path(r'^signup/$', core_view.Signup.as_view(), name='signup'),
  path(r'^$', core_view.UserList.as_view(), name='list_user_api'),
  path(r'^(?P<pk>[0-9]+)/$', core_view.UserDetail.as_view(), name='detail_user_api'),
]

Downloads/W3schools-With-Django-master/w3school/accounts/models.py
from django.db import models

# Create your models here.

Downloads/W3schools-With-Django-master/w3school/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .serializers import UserSerializer
from rest_framework import generics
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

class UserList(LoginRequiredMixin, generics.ListCreateAPIView):
  login_url = 'accounts:login'
  queryset = User.objects.all()
  serializer_class = UserSerializer


class UserDetail(LoginRequiredMixin, generics.RetrieveUpdateDestroyAPIView):
  login_url = 'accounts:login'
  queryset = User.objects.all()
  serializer_class = UserSerializer


class Signup(CreateView):
  form_class = UserCreationForm
  success_url = reverse_lazy('accounts:login')
  template_name = 'accounts/signup.html'


def home(request):
  return render(request, 'home.html')


def page1(request):
  return render(request, 'page1.html')


def page2(request):
  return render(request, 'page2.html')

Downloads/W3schools-With-Django-master/w3school/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Login Page
{% endblock %}

{% block content %}
  <h2>Login to W3schools website</h2>
  {% if form.errors %}
    <p style="color: red;">Your username and password didn`t match</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden", name="next" value="{{ next }}"/>
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red;">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: gray;">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Login</button>
    <a href="{% url 'accounts:signup' %}">Sign up</a>
  </form>
{% endblock %}

Downloads/W3schools-With-Django-master/w3school/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Sign up Page
{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-outline-info" type="submit">Sign up</button>
  </form>
{% endblock %}

Downloads/W3schools-With-Django-master/w3school/accounts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %} W3schools Website {% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/normalize.css'%}"/>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  {% include 'navbar.html' %}
  {% block content %}
  {% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

Downloads/W3schools-With-Django-master/w3school/accounts/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" style="color: #5AC8FA;font-size: 25px;" href="">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a style="font-size: 20px;" class="nav-link" href="">
          Home <span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a style="font-size: 20px; margin-top:12px;" href="{% url 'accounts:logout' %}" class="nav-link">logout</a>
        </li>
        <li class="nav-item">
          <a style="font-size: 20px; margin-top:12px;" href="" class="nav-link">
            {{ request.user.username }}
          </a>
        </li>
      {% else %}
        <li class="nav-item">
          <a href="{% url 'accounts:login' %}" class="nav-link">Sign in</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'accounts:signup' %}" class="nav-link">Sign up</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

Downloads/W3schools-With-Django-master/w3school/accounts/templates/page1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} W3schools Website {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css'%}"/>
    <link rel="stylesheet" href="{% static 'css/stylee.css' %}">
  </head>
  <body>
    <!-- start container -->
    <div class="row">
      <!-- start side menu -->
      <div class="xs">
        <h5>About</h5>
        <h5>Service</h5>
        <h5>Clients</h5>
        <h5>Contact</h5>
      </div>
      <!-- end side menu -->
      <div class="xx">
        <h1>Full Sidebar</h1>
        <p>This sidebar is of full height (100%) and always shown.</p>
        <p>Scroll this window to see the "fixed" effect.</p>
        <p>
          Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo,
          maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te,
          id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad.
          Eum no molestiae voluptatibus.
        </p>
        <p>
          Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo,
          maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te,
          id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad.
          Eum no molestiae voluptatibus.
        </p>
        <br><br><br><br><br><br>
      </div>
    </div>
    <!-- end container -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/home.js' %}"></script>
  </body>
</html>

Downloads/W3schools-With-Django-master/w3school/accounts/templates/page2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} W3schools Website {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css'%}"/>
    <link rel="stylesheet" href="{% static 'css/stylee.css' %}">
  </head>
  <body>
    <!-- start container -->
    <div class="row">
      <!-- start side menu -->
      <div class="xs1">
        <div style="background-color: #EDEDED;">
          <h5>About</h5>
          <h5>Service</h5>
          <h5>Clients</h5>
          <h5>Contact</h5>
        </div>
      </div>
      <!-- end side menu -->
      <div class="xx1">
        <h1>Auto Sidebar</h1>
        <p>This sidebar is as tall as its content (the links), and is always shown.</p>
        <p>Scroll this window to see the "fixed" effect.</p>
        <p>
          Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo,
          maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te,
          id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad.
          Eum no molestiae voluptatibus.
        </p>
        <p>
          Some text to enable scrolling.. Lorem ipsum dolor sit amet, illum definitiones no quo,
          maluisset concludaturque et eum, altera fabulas ut quo. Atqui causae gloriatur ius te,
          id agam omnis evertitur eum. Affert laboramus repudiandae nec et. Inciderint efficiantur his ad.
          Eum no molestiae voluptatibus.
        </p>
        <br><br><br><br><br><br>
      </div>
    </div>
    <!-- end container -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/home.js' %}"></script>
  </body>
</html>